config/routes.rb
Rails.application.routes.draw do
  resources :user_infos
  root to: "user_infos#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user_info.rb
class UserInfo < ApplicationRecord
    has_one_attached :image
    validates :full_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/user_infos_controller.rb
class UserInfosController < ApplicationController
  before_action :set_user_info, only: [:show, :edit, :update, :destroy]

  # GET /user_infos
  # GET /user_infos.json
  def index
    @user_infos = UserInfo.all
  end

  # GET /user_infos/1
  # GET /user_infos/1.json
  def show
  end

  # GET /user_infos/new
  def new
    @user_info = UserInfo.new
  end

  # GET /user_infos/1/edit
  def edit
  end

  # POST /user_infos
  # POST /user_infos.json
  def create
    @user_info = UserInfo.new(user_info_params)

    respond_to do |format|
      if @user_info.save
        format.html { redirect_to @user_info, notice: 'User info was successfully created.' }
        format.json { render :show, status: :created, location: @user_info }
      else
        format.html { render :new }
        format.json { render json: @user_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_infos/1
  # PATCH/PUT /user_infos/1.json
  def update
    respond_to do |format|
      if @user_info.update(user_info_params)
        format.html { redirect_to @user_info, notice: 'User info was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_info }
      else
        format.html { render :edit }
        format.json { render json: @user_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_infos/1
  # DELETE /user_infos/1.json
  def destroy
    @user_info.destroy
    respond_to do |format|
      format.html { redirect_to user_infos_url, notice: 'User info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_info
      @user_info = UserInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_info_params
      params.require(:user_info).permit(:full_name, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_infos_helper.rb
module UserInfosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/user_infos/_form.html.erb
<%= form_with(model: user_info, local: true) do |form| %>
  <% if user_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_info.errors.count, "error") %> prohibited this user_info from being saved:</h2>

      <ul>
      <% user_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :full_name %>
    <%= form.text_field :full_name %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_infos/edit.html.erb
<h1>Editing User Info</h1>

<%= render 'form', user_info: @user_info %>

<%= link_to 'Show', @user_info %> |
<%= link_to 'Back', user_infos_path %>

app/views/user_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Infos</h1>

<table>
  <thead>
    <tr>
      <th>Full name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_infos.each do |user_info| %>
      <tr>
        <td><%= user_info.full_name %></td>
        <td><%= link_to 'Show', user_info %></td>
        <td><%= link_to 'Edit', edit_user_info_path(user_info) %></td>
        <td><%= link_to 'Destroy', user_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Info', new_user_info_path %>

app/views/user_infos/new.html.erb
<h1>New User Info</h1>

<%= render 'form', user_info: @user_info %>

<%= link_to 'Back', user_infos_path %>

app/views/user_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Full name:</strong>
  <%= @user_info.full_name %>
</p>

<%= image_tag(@user_info.image, style: "width: 500px") %>
<br>
<br>
<%= link_to 'Edit', edit_user_info_path(@user_info) %> |
<%= link_to 'Back', user_infos_path %>